baseURL = "https://tiny.seedhost.eu/jeanmichel/downloads/html/CRITIQUES/cinema/"
languageCode = "fr"

# Pas de theme externe, on fait tout en layouts maison

[taxonomies]
  director = "directors"
  country  = "countries"

[params]
  # URL de base pour les medias heberges sur seedhost
  # Uploades a la main via WinSCP dans le dossier media/ sur le serveur
  mediaBaseURL = "https://tiny.seedhost.eu/jeanmichel/downloads/html/CRITIQUES/cinema/media"

[markup.goldmark.renderer]
  unsafe = true
